# build.yaml. This file is quite powerful, see https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      drift_dev:
        options:
          apply_converters_on_variables: true
          generate_values_in_copy_with: true
          scoped_dart_components: true
          named_parameters: true
          named_parameters_always_required: true
          sql:
            dialect: sqlite
            options:
              version: "3.38"