name: tagros_comptes
description: Pour compter les points au tagros
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
## versionCode = major * 10_000 + minor * 100 + patch
version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.4"

dependencies:
  another_flushbar: ^1.12.30 #Substitute for toasts and snackbars
  async: ^2.11.0
  collection: ^1.17.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  drift: ^2.10.0 # For reactive sql
  drift_dev: ^2.10.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_hooks: ^0.20.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.0
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^10.0.0
  google_mobile_ads: ^3.0.0
  hooks_riverpod: ^2.3.6
  intl: ^0.18.0
  lint: ^2.1.2
  mockito: ^5.4.2
  package_info_plus: ^4.1.0
  path: ^1.8.2
  path_provider: ^2.0.15
  #  flutter_stetho: ^0.5.2
  purchases_flutter: ^5.6.0
  riverpod_annotation: ^2.1.1
  rxdart: ^0.27.7
  sqlite3: ^2.0.0
  sqlite3_flutter_libs: ^0.5.15
  stack_trace: ^1.11.0
  timeago: ^3.5.0
  tuple: ^2.0.2
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.12

dev_dependencies:
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  custom_lint: ^0.4.0
  flutter_gen: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  go_router_builder: ^2.3.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  test: ^1.24.1

scripts:
  build: dart run build_runner build --delete-conflicting-outputs
  watch: dart run build_runner watch --delete-conflicting-outputs
  format: dart format lib/
  lint: dart analyze lib/
  test: dart test --coverage
  translations: dart pub global run intl_utils:generate

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true # For localisation

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo.png
    - images/logo_small.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/logo.png"
  remove_alpha_ios: true
flutter_native_splash:
  # Either color or background_image (not both)
  color: "#0e3d4f"
  #background_image: "assets/background.png"

  # Optional parameters
  image: images/logo_small.png
  branding: images/aroxoft.png
  branding_mode: bottom

  # Dark mode
  #branding_dark:
  #color_dark:
  #background_image_dark:
  #image_dark:

  # Set to false in order to disable generation for a specific platform
  android: true
  ios: true
  web: true

  # Position of splash image (android_gravity, ios_content_mode and web_image_mode)
  # android_gravity can be: bottom, center, center_horizontal, center_vertical, clip_horizontal, clip_vertical, end,
  # fill, fill_horizontal, fill_vertical, left, right, start, or top.
  #android_gravity: center
  # ios_content_mode can be: scaleToFill, scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft,
  # topRight, bottomLeft, or bottomRight.
  #ios_content_mode: center
  # web_image_mode can be: center, contain, stretch, and cover
  #web_image_mode: center

  # Uncomment to hide the notification bar (android/ios)
  #fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
