/// Flutter icons FlutterIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterIcons
///      fonts:
///       - asset: fonts/FlutterIcons.ttf
///
///
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FlutterIcons {
  FlutterIcons._();

  static const _kFontFam = 'FlutterIcons';
  static const String? _kFontPkg = null;

  static const IconData cloversCard = IconData(0xe96b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attack = IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamondsCard = IconData(0xe993, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartsCard = IconData(0xe9f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData defense = IconData(0xea96, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spadesCard = IconData(0xeaa9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idBadge = IconData(0xf2c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
