name: Run ios build

on:
  pull_request:
    branches: [ main ]
  merge_group:
    types: [ checks_requested ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: dart-lang/setup-dart@v1
        with:
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - name: build the environment
        env:
          ANDROID_APP_ID: ${{ secrets.ANDROID_APP_ID }}
          ANDROID_BANNER_ID: ${{ secrets.ANDROID_BANNER_ID }}
          ANDROID_NATIVE_ID: ${{ secrets.ANDROID_NATIVE_ID }}
          IOS_APP_ID: ${{ secrets.IOS_APP_ID }}
          IOS_BANNER_ID: ${{ secrets.IOS_BANNER_ID }}
          IOS_NATIVE_ID: ${{ secrets.IOS_NATIVE_ID }}
          TEST_ADS: ${{ secrets.TEST_ADS }}
        run: dart tool/env.dart
      - run: flutter test
      - name: Decode keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: echo $KEYSTORE_BASE64 | base64 --decode > android/app/key.jks
      - name: Decode key.properties
        env:
          KEY_PROPERTIES_BASE64: ${{ secrets.KEY_PROPERTIES_BASE64 }}
        run: echo $KEY_PROPERTIES_BASE64 | base64 --decode > android/key.properties
      - run: flutter build appbundle --release
      - name: Upload app bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: 'x64'
      - uses: dart-lang/setup-dart@v1
        with:
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - name: build the environment
        env:
          ANDROID_APP_ID: ${{ secrets.ANDROID_APP_ID }}
          ANDROID_BANNER_ID: ${{ secrets.ANDROID_BANNER_ID }}
          ANDROID_NATIVE_ID: ${{ secrets.ANDROID_NATIVE_ID }}
          IOS_APP_ID: ${{ secrets.IOS_APP_ID }}
          IOS_BANNER_ID: ${{ secrets.IOS_BANNER_ID }}
          IOS_NATIVE_ID: ${{ secrets.IOS_NATIVE_ID }}
          TEST_ADS: ${{ secrets.TEST_ADS }}
        run: dart tool/env.dart
      - run: flutter test
      - run: flutter build ios --release --no-codesign
      - name: Upload ios app
        uses: actions/upload-artifact@v2
        with:
          name: app-release-ipa
          path: build/ios/archive/Runner.xcarchive
