name: Run tests
run-name: >
  ${{ github.event.pull_request.title }} - ${{ github.workflow }} (#${{ github.run_number }}.${{ github.run_attempt }}) - ${{ github.event_name }} ${{ github.ref }} (from ${{ github.head_ref }} to ${{ github.base_ref }})

on:
  pull_request:
    branches: [ dev ]
  merge_group:
    types: [ checks_requested ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - name: Generate files (freezed, json_serializable)
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Generate translations
        run: |
          flutter pub global activate intl_utils && flutter pub global run intl_utils:generate
      - name: Analyze code
        run: flutter analyze --no-fatal-infos --fatal-warnings
      - run: flutter test
